### ISSUE TITLE
"Collapse" states that have already voted

### ISSUE THREAD

**Issue by nickolaos** [francisli/primarytracker#19]

**Comment by francisli** [comment]
Hi @nickolaos thanks for filing the issue, I am working on updating the site now that voting is actually occurring...! I'm planning on adding a delegate count tracker for the candidates as well...!

**Comment by francisli** [comment]
The site has been updated- polls are now hidden by default for states in which their primary or caucus has passed, and the delegate count results are now shown instead. Links by the state name allow you to hide/show the polls/results.
